### ISSUE TITLE
Transfer repository to JuliaDocs

### ISSUE THREAD

**Issue by kimikage** [JuliaDocs/ANSIColoredPrinters.jl#10]
As suggested in https://github.com/JuliaDocs/Documenter.jl/pull/1441#pullrequestreview-516406244

- ~Add @kimikage to JuliaDocs members (to create the repository)~
  - Once the transfer is complete, I'm fine with being an outside collaborator
- [x] Hit the transfer button
- [x] Update URLs (PR #14)
- [x] Update CI setting (e.g. DOCUMENTER_KEY)

BTW, I don't care about the default branch name, so I just use the default name. As a result, this repository uses the "main". If you prefer "master", you can change the name.

**Comment by mortenpi** [comment]
I think you should just be able to request the transfer of this repository to JuliaDocs under "Settings > Danger Zone > Transfer ownership"?

**Comment by kimikage** [comment]
Yes, that's what I thought at first, but the requirements for transferring to an organization seem to be different.

> To transfer a repository that you own to an organization, you must have permission to create a repository in the target organization.

https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/transferring-a-repository#about-repository-transfers

In fact, I got the following error message:

> You don’t have the permission to create public repositories on JuliaDocs

**Comment by mortenpi** [comment]
Interesting. Can you transfer it to my personal user and then I'll move it under JuliaDocs?

**Comment by kimikage** [comment]
It seems to have transferred successfully. Thank you @mortenpi!
