### ISSUE TITLE
Package registration

### ISSUE THREAD

**Issue by kimikage** [JuliaDocs/ANSIColoredPrinters.jl#15]
This package is not yet mature, but I would like to register the package early for experimental use e.g. in https://github.com/JuliaDocs/Documenter.jl/pull/1441. For the time being, it will be developed as v0.1.x even with "minor" breaking changes.

If you have anything to be discussed before registering the package, please comment here or in #4.

**Comment by mortenpi** [comment]
It should also be possible to register it with v0.0.1. That way the minor breaking changes wouldn't be a problem from a SemVer perspective.

**Comment by kimikage** [comment]
Okay, we are currently waiting for the registration.
https://github.com/JuliaRegistries/General/pull/25217

**Comment by kimikage** [comment]
v0.0.1 has been registered.:tada:
